//User Actions
export const FETCH_USER = "FETCH_USER"
export const CREATE_USER = "CREATE_USER"

//Data Actions
export const FETCH_TRACKER_DATA = "FETCH_TRACKER_DATA"
export const FETCH_TRACKER_STATE_DATA = "FETCH_TRACKER_STATE_DATA"
export const FETCH_TRACKER_STATE_CITY_DATA = "FETCH_TRACKER_STATE_CITY_DATA"