//Employee Actions
export const FETCH_ALL_EMPLOYEES = "FETCH_EMPLOYEES"
export const FETCH_EMPLOYEE = "FETCH_EMPLOYEE"
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE"
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE"
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"

//Manager Actions
export const FETCH_MANAGER = "FETCH_MANAGER"
export const CREATE_MANAGER = "CREATE_MANAGER"